require "user.options"
require "user.keymaps"
require "user.plugins"

require "user.gruvbox"
require "user.telescope"
require "user.treesitter"
require "user.lualine"
require "user.gitsigns"
require "user.cmp"
require "user.neotest"
require "user.autopairs"
require "user.nvim-tree"
