---
editor: vim
colorize: true
style: monokai
formatter: terminal16m
pager: less -FRX
cheatpaths:
  - name: community
    path: ~/.config/cheat/cheatsheets/community
    tags: [ community ]
    readonly: true

  - name: personal
    path: ~/.config/cheat/cheatsheets/personal
    tags: [ personal ]
    readonly: false
