return {
  "nvim-treesitter/nvim-treesitter",
  branch = 'master',
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ignore_install = {},
    sync_install = false,
    auto_install = false,
    folds = {
      enable = true
    },
    highlight = {
      enable = true,
      disable = { "markdown" },
      additional_vim_regex_highlighting = false,
    },
    indent = {
      enable = true,
      disable = { "yaml" },
    },
    ensure_installed = {
      "bash",
      "c",
      "comment",
      "css",
      "diff",
      "dockerfile",
      "fish",
      "git_rebase",
      "gitignore",
      "go",
      "gomod",
      "graphql",
      "hcl",
      "html",
      "http",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "printf",
      "python",
      "query",
      "regex",
      "ruby",
      "rust",
      "scheme",
      "scss",
      "slim",
      "sql",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    }
  }
}
